/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheRollerRouteImport } from './routes/the-roller'
import { Route as TheRitualBundleRouteImport } from './routes/the-ritual-bundle'
import { Route as TheRitualRouteImport } from './routes/the-ritual'
import { Route as TheOilRouteImport } from './routes/the-oil'
import { Route as TheMatRouteImport } from './routes/the-mat'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TheRollerRoute = TheRollerRouteImport.update({
  id: '/the-roller',
  path: '/the-roller',
  getParentRoute: () => rootRouteImport,
} as any)
const TheRitualBundleRoute = TheRitualBundleRouteImport.update({
  id: '/the-ritual-bundle',
  path: '/the-ritual-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const TheRitualRoute = TheRitualRouteImport.update({
  id: '/the-ritual',
  path: '/the-ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const TheOilRoute = TheOilRouteImport.update({
  id: '/the-oil',
  path: '/the-oil',
  getParentRoute: () => rootRouteImport,
} as any)
const TheMatRoute = TheMatRouteImport.update({
  id: '/the-mat',
  path: '/the-mat',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/the-mat': typeof TheMatRoute
  '/the-oil': typeof TheOilRoute
  '/the-ritual': typeof TheRitualRoute
  '/the-ritual-bundle': typeof TheRitualBundleRoute
  '/the-roller': typeof TheRollerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/the-mat': typeof TheMatRoute
  '/the-oil': typeof TheOilRoute
  '/the-ritual': typeof TheRitualRoute
  '/the-ritual-bundle': typeof TheRitualBundleRoute
  '/the-roller': typeof TheRollerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/the-mat': typeof TheMatRoute
  '/the-oil': typeof TheOilRoute
  '/the-ritual': typeof TheRitualRoute
  '/the-ritual-bundle': typeof TheRitualBundleRoute
  '/the-roller': typeof TheRollerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/refund-policy'
    | '/terms'
    | '/the-mat'
    | '/the-oil'
    | '/the-ritual'
    | '/the-ritual-bundle'
    | '/the-roller'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/refund-policy'
    | '/terms'
    | '/the-mat'
    | '/the-oil'
    | '/the-ritual'
    | '/the-ritual-bundle'
    | '/the-roller'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/refund-policy'
    | '/terms'
    | '/the-mat'
    | '/the-oil'
    | '/the-ritual'
    | '/the-ritual-bundle'
    | '/the-roller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  TheMatRoute: typeof TheMatRoute
  TheOilRoute: typeof TheOilRoute
  TheRitualRoute: typeof TheRitualRoute
  TheRitualBundleRoute: typeof TheRitualBundleRoute
  TheRollerRoute: typeof TheRollerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-roller': {
      id: '/the-roller'
      path: '/the-roller'
      fullPath: '/the-roller'
      preLoaderRoute: typeof TheRollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-ritual-bundle': {
      id: '/the-ritual-bundle'
      path: '/the-ritual-bundle'
      fullPath: '/the-ritual-bundle'
      preLoaderRoute: typeof TheRitualBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-ritual': {
      id: '/the-ritual'
      path: '/the-ritual'
      fullPath: '/the-ritual'
      preLoaderRoute: typeof TheRitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-oil': {
      id: '/the-oil'
      path: '/the-oil'
      fullPath: '/the-oil'
      preLoaderRoute: typeof TheOilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-mat': {
      id: '/the-mat'
      path: '/the-mat'
      fullPath: '/the-mat'
      preLoaderRoute: typeof TheMatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  TheMatRoute: TheMatRoute,
  TheOilRoute: TheOilRoute,
  TheRitualRoute: TheRitualRoute,
  TheRitualBundleRoute: TheRitualBundleRoute,
  TheRollerRoute: TheRollerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
